# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 05:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170418_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente'),
        ),
    ]
