# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170418_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=35)),
                ('quantidade', models.IntegerField(default=0)),
                ('minimo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
