# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 06:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('codigo', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('pedido', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('recebimento', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fornecedor')),
            ],
        ),
    ]
